spring:
  profiles:
    active: dev
logging:
  file: live.log
  level:
    com.live.dao: info

mybatis:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/**/*.xml

pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: false
token:
  expirationSeconds: 300
  validTime: 7