spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.58.173:3306/pet_family?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: sd123456
    db-type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 256
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: r-wz9pzuxsgm5u1gmpv2pd.redis.rds.aliyuncs.com
    password: z4e@1zoF25cPlDvY
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 2
    database: 2

  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
server:
  port: 18081

redis:
  prefix: njm_
  token: token_uid_

baiduAddress:
  url: http://api.map.baidu.com/geocoding/v3/
  key: gUcIf1KKVyKbHYKnZ0lHt1ISojBwfk1x
