spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yundiancs.mysql.polardb.rds.aliyuncs.com:3306/ydcs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: ceshi
    password: uP8ICbwQDp52EZ6v
    db-type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 256
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: r-wz9pzuxsgm5u1gmpv2pd.redis.rds.aliyuncs.com
    password: z4e@1zoF25cPlDvY
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 2
    database: 2
server:
  port: 18081

redis:
  prefix: njm_
  token: token_uid_


